/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectosequence;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class Configuracion extends javax.swing.JFrame {

    SistemaUsuarios sistemaUsuarios;

    public Configuracion() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        sistemaUsuarios = new SistemaUsuarios();
        int configCantJugadores = sistemaUsuarios.getPlayersConfig();
        ColorItem renderer = new ColorItem();
        cb_Color.setRenderer(renderer);
        ArrayList<String> fichasDisponibles = sistemaUsuarios.getFichas();
         
        for (String ficha : fichasDisponibles) {
            String name = ficha.split(".png")[0];
            cb_Color.addItem(name);
        }
        for (int i = 0; i < cb_Color.getItemCount(); i++) {
            boolean isSelectedIcon = cb_Color.getItemAt(i).equals(sistemaUsuarios.getUsuarioLogeado().fichaFile.getName().split(".png")[0]);
            if (isSelectedIcon) {
                cb_Color.setSelectedIndex(i);
            }
        }
        
        switch (configCantJugadores) {
            case 2:
                btn2players.setBackground(Color.PINK);
                break;
            case 3:
                btn3players.setBackground(Color.PINK);
                break;
            case 4:
                btn4players.setBackground(Color.PINK);
                break;
            case 6:
                btn6players.setBackground(Color.PINK);
                break;
            case 8:
                btn8players.setBackground(Color.PINK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn8players = new javax.swing.JButton();
        btnRegresarAMenuPrincipal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn3players = new javax.swing.JButton();
        btn4players = new javax.swing.JButton();
        btn6players = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn2players = new javax.swing.JButton();
        cb_Color = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Color de ficha");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 180, 30));

        btn8players.setBackground(new java.awt.Color(0, 0, 102));
        btn8players.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        btn8players.setForeground(new java.awt.Color(255, 255, 255));
        btn8players.setText("8 Players");
        btn8players.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn8players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8playersActionPerformed(evt);
            }
        });
        jPanel1.add(btn8players, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 130, 70));

        btnRegresarAMenuPrincipal.setBackground(new java.awt.Color(255, 51, 51));
        btnRegresarAMenuPrincipal.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnRegresarAMenuPrincipal.setText("Regresar");
        btnRegresarAMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarAMenuPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarAMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 150, 70));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Configuracion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 170, 30));

        btn3players.setBackground(new java.awt.Color(0, 0, 102));
        btn3players.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        btn3players.setForeground(new java.awt.Color(255, 255, 255));
        btn3players.setText("3 Players");
        btn3players.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn3players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3playersActionPerformed(evt);
            }
        });
        jPanel1.add(btn3players, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 120, 70));

        btn4players.setBackground(new java.awt.Color(0, 0, 102));
        btn4players.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        btn4players.setForeground(new java.awt.Color(255, 255, 255));
        btn4players.setText("4 Players");
        btn4players.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn4players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4playersActionPerformed(evt);
            }
        });
        jPanel1.add(btn4players, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 120, 70));

        btn6players.setBackground(new java.awt.Color(0, 0, 102));
        btn6players.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        btn6players.setForeground(new java.awt.Color(255, 255, 255));
        btn6players.setText("6  Players");
        btn6players.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn6players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6playersActionPerformed(evt);
            }
        });
        jPanel1.add(btn6players, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 120, 70));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad de jugadores");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 280, 30));

        btn2players.setBackground(new java.awt.Color(0, 0, 102));
        btn2players.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        btn2players.setForeground(new java.awt.Color(255, 255, 255));
        btn2players.setText("2 Players");
        btn2players.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn2players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2playersActionPerformed(evt);
            }
        });
        jPanel1.add(btn2players, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 120, 70));

        jPanel1.add(cb_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 190, -1));

        btnGuardar.setBackground(new java.awt.Color(255, 51, 51));
        btnGuardar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 150, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void configurarJugadores(int numJugadores) {
        sistemaUsuarios.setPlayersConfig(numJugadores);
        JOptionPane.showMessageDialog(null, "Configuración guardada exitosamente", "Slayy", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }

    private void btn8playersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8playersActionPerformed
        configurarJugadores(8);
    }//GEN-LAST:event_btn8playersActionPerformed

    private void btnRegresarAMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarAMenuPrincipalActionPerformed
        MenuInicio menuinicio = new MenuInicio();
        menuinicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarAMenuPrincipalActionPerformed

    private void btn3playersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3playersActionPerformed
        // TODO add your handling code here:
        configurarJugadores(3);
    }//GEN-LAST:event_btn3playersActionPerformed

    private void btn4playersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4playersActionPerformed
        // TODO add your handling code here:
        configurarJugadores(4);
    }//GEN-LAST:event_btn4playersActionPerformed

    private void btn6playersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6playersActionPerformed
        // TODO add your handling code here:
        configurarJugadores(6);
    }//GEN-LAST:event_btn6playersActionPerformed

    private void btn2playersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2playersActionPerformed
        // TODO add your handling code here:
        configurarJugadores(2);
    }//GEN-LAST:event_btn2playersActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String selectedIcon = (String) cb_Color.getSelectedItem();
        sistemaUsuarios.setusuarioLogeadoFicha(selectedIcon);
        JOptionPane.showMessageDialog(null, "Ficha actualizada correctamente!");
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2players;
    private javax.swing.JButton btn3players;
    private javax.swing.JButton btn4players;
    private javax.swing.JButton btn6players;
    private javax.swing.JButton btn8players;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresarAMenuPrincipal;
    private javax.swing.JComboBox<String> cb_Color;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
