package proyectosequence;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Gabriela
 */
public class Juego extends javax.swing.JFrame {

    Tablero tablero;
    List<CartasBaraja> jugador1;
    List<CartasBaraja> jugador2;

    JButton[] mano;
    String cartaSeleccionadaTexto;
    public int turno;

    //Imagen de parte trasera de la baraja
    ImageIcon imagenTrasero;
    ImageIcon A_corazones;
    ImageIcon A_diamantes;
    ImageIcon A_picas;
    ImageIcon A_trebol;
    HashMap<String, String> cartasConImagenes = new HashMap<>();
    Baraja baraja = new Baraja();

    public Juego(MenuInicio mainWindow) throws MalformedURLException {
        initComponents();
        
        this.turno = 1;
        mano = new JButton[7];
        mano[1] = carta1;
        mano[2] = carta2;
        mano[3] = carta3;
        mano[4] = carta4;
        mano[5] = carta5;
        mano[6] = carta6;

        //asociarCartasConImagenes();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        gamePanel.setLayout(new GridLayout(1, 1));
        setResizable(false);
        tablero = new Tablero(this, mainWindow);
        gamePanel.add(tablero);
        gamePanel.repaint();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
        tablero.startTurnTimer();

        baraja.barajar();

        jugador1 = baraja.repartir(6);
        jugador2 = baraja.repartir(6);

        ponerTextoMano();
        ponerImagenesEnMano();
        actualizarLabelTurno();

    }

    public JLabel getTimerLabel() {
        return timer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        timer = new javax.swing.JLabel();
        gamePanel = new javax.swing.JPanel();
        carta1 = new javax.swing.JButton();
        carta6 = new javax.swing.JButton();
        carta2 = new javax.swing.JButton();
        carta3 = new javax.swing.JButton();
        carta4 = new javax.swing.JButton();
        carta5 = new javax.swing.JButton();
        barajaDeCartas = new javax.swing.JLabel();
        lblturno = new javax.swing.JLabel();
        btnDescartarCarta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timer.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        timer.setForeground(new java.awt.Color(255, 204, 255));
        timer.setText("temporizador");
        jPanel1.add(timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        gamePanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel1.add(gamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 590, 580));

        carta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta1ActionPerformed(evt);
            }
        });
        jPanel1.add(carta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, 100, 110));

        carta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta6ActionPerformed(evt);
            }
        });
        jPanel1.add(carta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 610, 100, 110));

        carta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta2ActionPerformed(evt);
            }
        });
        jPanel1.add(carta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 610, 100, 110));

        carta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta3ActionPerformed(evt);
            }
        });
        jPanel1.add(carta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, 100, 110));

        carta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta4ActionPerformed(evt);
            }
        });
        jPanel1.add(carta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 610, 100, 110));

        carta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carta5ActionPerformed(evt);
            }
        });
        jPanel1.add(carta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 610, 100, 110));

        barajaDeCartas.setBackground(new java.awt.Color(255, 255, 255));
        barajaDeCartas.setText("parte trasera mazo");
        barajaDeCartas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        barajaDeCartas.setOpaque(true);
        jPanel1.add(barajaDeCartas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 100, 110));

        lblturno.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        lblturno.setForeground(new java.awt.Color(255, 204, 255));
        lblturno.setText("dos jugadores");
        jPanel1.add(lblturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 90, -1, -1));

        btnDescartarCarta.setText("Descartar Carta");
        btnDescartarCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarCartaActionPerformed(evt);
            }
        });
        jPanel1.add(btnDescartarCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1213, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarLabelTurno(){
        lblturno.setText("Turno de jugador "+turno);
    }
    private void carta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carta1ActionPerformed

        // itera a través de las casillas del tablero para quitar las cartas resaltadas
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                tablero.casillas[i][j].label.setBackground(null);
                tablero.casillas[i][j].label.setOpaque(false);
            }
        }

        String textocarta = carta1.getText();
        cartaSeleccionadaTexto = textocarta;

        // itera a través de las casillas del tablero
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                if (tablero.casillas[i][j].carta != null && tablero.casillas[i][j].carta.getNombre().equals(textocarta)) {
                    // si la casilla del tablero coincide con el texto del botón clickeado, se pone azul
                    tablero.casillas[i][j].label.setBackground(Color.BLUE);
                    tablero.casillas[i][j].label.setOpaque(true);
                }
            }
        }
    }//GEN-LAST:event_carta1ActionPerformed

    public void eliminarYAgregarCarta() {
               
        for (int i = 0; i < 6; i++) {
            if (turno == 1) {
                if (jugador1.get(i).toString().equals(cartaSeleccionadaTexto)) {
                    jugador1.remove(i);
                    CartasBaraja nuevaCarta = baraja.repartir(1).get(0); // sacar la nueva carta de la baraja
                    jugador1.add(nuevaCarta);
                    ponerTextoMano();
                    ponerImagenesEnMano();
                    break;
                }
            }else if(turno ==2){
               if (jugador2.get(i).toString().equals(cartaSeleccionadaTexto)) {
                    jugador2.remove(i);
                    CartasBaraja nuevaCarta = baraja.repartir(1).get(0); // sacar la nueva carta de la baraja
                    jugador2.add(nuevaCarta);
                    ponerTextoMano();
                    ponerImagenesEnMano();
                    break;
                } 
            }
        }
    }

    private void carta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carta2ActionPerformed
        // itera a través de las casillas del tablero para quitar las cartas resaltadas
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                tablero.casillas[i][j].label.setBackground(null);
                tablero.casillas[i][j].label.setOpaque(false);
            }
        }

        String textocarta = carta2.getText();
        cartaSeleccionadaTexto = textocarta;
        // itera a través de las casillas del tablero
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                if (tablero.casillas[i][j].carta != null && tablero.casillas[i][j].carta.getNombre().equals(textocarta)) {
                    // si la casilla del tablero coincide con el texto del botón clickeado, se pone azul
                    tablero.casillas[i][j].label.setBackground(Color.BLUE);
                    tablero.casillas[i][j].label.setOpaque(true);
                }
            }
        }
    }//GEN-LAST:event_carta2ActionPerformed

    private void carta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carta3ActionPerformed
        // itera a través de las casillas del tablero para quitar las cartas resaltadas
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                tablero.casillas[i][j].label.setBackground(null);
                tablero.casillas[i][j].label.setOpaque(false);
            }
        }

        String textocarta = carta3.getText();
        cartaSeleccionadaTexto = textocarta;
        // itera a través de las casillas del tablero
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                if (tablero.casillas[i][j].carta != null && tablero.casillas[i][j].carta.getNombre().equals(textocarta)) {
                    // si la casilla del tablero coincide con el texto del botón clickeado, se pone azul
                    tablero.casillas[i][j].label.setBackground(Color.BLUE);
                    tablero.casillas[i][j].label.setOpaque(true);
                }
            }
        }
    }//GEN-LAST:event_carta3ActionPerformed

    private void carta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carta4ActionPerformed
        // itera a través de las casillas del tablero para quitar las cartas resaltadas
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                tablero.casillas[i][j].label.setBackground(null);
                tablero.casillas[i][j].label.setOpaque(false);
            }
        }

        String textocarta = carta4.getText();
        cartaSeleccionadaTexto = textocarta;
        // itera a través de las casillas del tablero
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                if (tablero.casillas[i][j].carta != null && tablero.casillas[i][j].carta.getNombre().equals(textocarta)) {
                    // si la casilla del tablero coincide con el texto del botón clickeado, se pone azul
                    tablero.casillas[i][j].label.setBackground(Color.BLUE);
                    tablero.casillas[i][j].label.setOpaque(true);
                }
            }
        }
    }//GEN-LAST:event_carta4ActionPerformed

    private void carta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carta5ActionPerformed

        // itera a través de las casillas del tablero para quitar las cartas resaltadas
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                tablero.casillas[i][j].label.setBackground(null);
                tablero.casillas[i][j].label.setOpaque(false);
            }
        }

        String textocarta = carta5.getText();
        cartaSeleccionadaTexto = textocarta;
        // itera a través de las casillas del tablero
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                if (tablero.casillas[i][j].carta != null && tablero.casillas[i][j].carta.getNombre().equals(textocarta)) {
                    // si la casilla del tablero coincide con el texto del botón clickeado, se pone azul
                    tablero.casillas[i][j].label.setBackground(Color.BLUE);
                    tablero.casillas[i][j].label.setOpaque(true);
                }
            }
        }
    }//GEN-LAST:event_carta5ActionPerformed

    private void carta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carta6ActionPerformed
        // itera a través de las casillas del tablero para quitar las cartas resaltadas
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                tablero.casillas[i][j].label.setBackground(null);
                tablero.casillas[i][j].label.setOpaque(false);
            }
        }

        String textocarta = carta6.getText();
        cartaSeleccionadaTexto = textocarta;
        // itera a través de las casillas del tablero
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                if (tablero.casillas[i][j].carta != null && tablero.casillas[i][j].carta.getNombre().equals(textocarta)) {
                    // si la casilla del tablero coincide con el texto del botón clickeado, se pone azul
                    tablero.casillas[i][j].label.setBackground(Color.BLUE);
                    tablero.casillas[i][j].label.setOpaque(true);
                }
            }
        }
    }//GEN-LAST:event_carta6ActionPerformed

    private void btnDescartarCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarCartaActionPerformed
        if(cartaSeleccionadaTexto==null){
            JOptionPane.showMessageDialog(null, "Seleccione primero una carta y luego dele a descartar.");
        }else{
        eliminarYAgregarCarta();
        ponerTextoMano();
        ponerImagenesEnMano();
            
        }
        
    }//GEN-LAST:event_btnDescartarCartaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Juego(null).setVisible(true);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(Juego.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    //Solo pone el texto a los botones 
    private void ponerTextoMano() {
        if (turno == 1) {
            carta1.setText(jugador1.get(1 - 1).toString());
            carta2.setText(jugador1.get(2 - 1).toString());
            carta3.setText(jugador1.get(3 - 1).toString());
            carta4.setText(jugador1.get(4 - 1).toString());
            carta5.setText(jugador1.get(5 - 1).toString());
            carta6.setText(jugador1.get(6 - 1).toString());
        }
        if (turno == 2) {
            carta1.setText(jugador2.get(1 - 1).toString());
            carta2.setText(jugador2.get(2 - 1).toString());
            carta3.setText(jugador2.get(3 - 1).toString());
            carta4.setText(jugador2.get(4 - 1).toString());
            carta5.setText(jugador2.get(5 - 1).toString());
            carta6.setText(jugador2.get(6 - 1).toString());
        }

    }

    public void cambioDeTurno() {
        // itera a través de las casillas del tablero para quitar las cartas resaltadas
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                tablero.casillas[i][j].label.setBackground(null);
                tablero.casillas[i][j].label.setOpaque(false);
            }
        }
        eliminarYAgregarCarta();
        turno++;
        //Reiniciar el turno
        if (turno > 2) {
            turno = 1;
        }
        ponerTextoMano();
        ponerImagenesEnMano();
        actualizarLabelTurno();

    }

    //Poner imagenes a los botones de la mano
    private void ponerImagenMano(JButton boton) {
        String textoDeCartaAgarrada = boton.getText();
        //ruta de la imagen
        String rutaImagen = "/img/" + textoDeCartaAgarrada + ".png";

        URL urlCartaAgarrada = getClass().getResource(rutaImagen);

        if (urlCartaAgarrada != null) {
            ImageIcon imagenCarta = new ImageIcon(urlCartaAgarrada);
            int nuevoAncho = 90;
            int nuevoAlto = 100;
            Image imagenRedimensionada = imagenCarta.getImage().getScaledInstance(nuevoAncho, nuevoAlto, Image.SCALE_SMOOTH);

            boton.setIcon(new ImageIcon(imagenRedimensionada));
        } else {
            System.err.println("No se pudo encontrar la imagen en la ruta: " + rutaImagen);
        }
    }

    //Poner imagen a cada boton
    private void ponerImagenesEnMano() {
        ponerImagenMano(carta1);
        ponerImagenMano(carta2);
        ponerImagenMano(carta3);
        ponerImagenMano(carta4);
        ponerImagenMano(carta5);
        ponerImagenMano(carta6);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barajaDeCartas;
    private javax.swing.JButton btnDescartarCarta;
    private javax.swing.JButton carta1;
    private javax.swing.JButton carta2;
    private javax.swing.JButton carta3;
    private javax.swing.JButton carta4;
    private javax.swing.JButton carta5;
    private javax.swing.JButton carta6;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblturno;
    private javax.swing.JLabel timer;
    // End of variables declaration//GEN-END:variables
}
