package proyectosequence;

import java.util.ArrayList;

/**
 *
 * @author danie
 */
public class Reportes extends javax.swing.JFrame {

    SistemaUsuarios sistemausuarios;

    public Reportes() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        sistemausuarios = new SistemaUsuarios();
        ArrayList<Jugador> usuarios = sistemausuarios.getListaUsuarios();
        String[] reportes = new String[usuarios.size()];
        for (int i = 0; i < usuarios.size(); i++) {
            reportes[i] = "\nUsuario: " + usuarios.get(i).getUsername() + ", \nPuntos: " + usuarios.get(i).getPuntos() + "\nFecha: " + usuarios.get(i).getFormattedFechaCreacion();
        }
        tahistorialjuegos.setListData(reportes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnregresarconfig = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tahistorialjuegos = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reportes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, 62));

        btnregresarconfig.setBackground(new java.awt.Color(153, 0, 0));
        btnregresarconfig.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        btnregresarconfig.setForeground(new java.awt.Color(255, 204, 255));
        btnregresarconfig.setText("Regresar");
        btnregresarconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarconfigActionPerformed(evt);
            }
        });
        jPanel1.add(btnregresarconfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 210, 80));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel6.setText("descripción de mis últimos juegos");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 680, 60));

        tahistorialjuegos.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(tahistorialjuegos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 1020, 270));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/Reportes.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnregresarconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarconfigActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnregresarconfigActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregresarconfig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> tahistorialjuegos;
    // End of variables declaration//GEN-END:variables
}
