package proyectosequence;

import java.util.ArrayList;

/**
 *
 * @author danie
 */
public class Reportes extends javax.swing.JFrame {

    SistemaUsuarios sistemausuarios;

    public Reportes(SistemaUsuarios sistemausuarios) {
        this.sistemausuarios=sistemausuarios;
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tahistorialjuegos.setEditable(false);
        sistemausuarios = new SistemaUsuarios();
        ArrayList<Jugador> usuarios = sistemausuarios.getListaUsuarios();
        String[] reportes = new String[usuarios.size()];
        for (int i = 0; i < usuarios.size(); i++) {
            reportes[i] = "\nUsuario: " + usuarios.get(i).getUsername() + ", \nPuntos: " + usuarios.get(i).getPuntos() + "\nFecha: " + usuarios.get(i).getFormattedFechaCreacion();
        }
        taUsuarios.setListData(reportes);
        
        Jugador usuariologeado = sistemausuarios.getUsuarioLogeado();
        lblUsuarioLogeado.setText("Usuario logeado " + usuariologeado.getNombreCompleto());
        ponerHistorialJuegos(usuariologeado);
        System.out.println("El usuario logeado es: " + usuariologeado.getNombreCompleto() + " con usuario: " + usuariologeado.getUsername());
        System.out.println("Los logs del usuario "+usuariologeado.usuario+ " son: " + usuariologeado.getLogs());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnregresarconfig = new javax.swing.JButton();
        lblUsuarioLogeado = new javax.swing.JLabel();
        lblRanking = new javax.swing.JLabel();
        lblLogs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taUsuarios = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tahistorialjuegos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reportes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, 62));

        btnregresarconfig.setBackground(new java.awt.Color(153, 0, 0));
        btnregresarconfig.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        btnregresarconfig.setForeground(new java.awt.Color(255, 204, 255));
        btnregresarconfig.setText("Regresar");
        btnregresarconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarconfigActionPerformed(evt);
            }
        });
        jPanel1.add(btnregresarconfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 680, 210, 80));

        lblUsuarioLogeado.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuarioLogeado.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        lblUsuarioLogeado.setText("descripción de mis últimos juegos");
        jPanel1.add(lblUsuarioLogeado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 680, 60));

        lblRanking.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblRanking.setForeground(new java.awt.Color(0, 0, 0));
        lblRanking.setText("RANKING");
        jPanel1.add(lblRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        lblLogs.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblLogs.setForeground(new java.awt.Color(0, 0, 0));
        lblLogs.setText("LOGS");
        jPanel1.add(lblLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, -1));

        taUsuarios.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(taUsuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 1020, 140));

        tahistorialjuegos.setColumns(20);
        tahistorialjuegos.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        tahistorialjuegos.setRows(5);
        jScrollPane3.setViewportView(tahistorialjuegos);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 1020, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/Reportes.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ponerHistorialJuegos(Jugador usuarioLogeado) {
        String logsUsuarioLogeado = usuarioLogeado.getLogs();
        if (logsUsuarioLogeado.equals("")) {
            tahistorialjuegos.setText("No se han jugado partidas aun.");
        } else {
            tahistorialjuegos.setText(logsUsuarioLogeado);
        }
    }

    private void btnregresarconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarconfigActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnregresarconfigActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregresarconfig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLogs;
    private javax.swing.JLabel lblRanking;
    private javax.swing.JLabel lblUsuarioLogeado;
    private javax.swing.JList<String> taUsuarios;
    private javax.swing.JTextArea tahistorialjuegos;
    // End of variables declaration//GEN-END:variables
}
